apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow

on:
  push:
    branches:
      - '**'

jobs:
  build:
    steps:
      - name: Say hello thi sis a ver ver very very very long name and I want to see how it looks
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world"
