apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Test docker and native
on:
  workflow_dispatch:
jobs:
  hello_preconf_action:
    steps:
      - name: Say hello
        uses: mlcb_checkout
    runs-on:
      - my-label-3
  hello_action:
    steps:
      - name: Say hello
        uses: cloudbees-io/checkout@v1
    runs-on:
      - my-label-3
  hello_docker:
    steps:
      - name: Say hello
        run: |
          echo "Hello world! I'm $(whoami) on $(hostname)"
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
    runs-on:
      - docker,my-label-3
  hello_native:
    steps:
      - name: Say hello
        run: |
          echo "Hello world! I'm $(whoami) on $(hostname)"
        shell: sh
    runs-on:
      - native,my-label-3
  hello_tekton:
    steps:
      - name: Say hello
        run: |
          echo "Hello world! I'm $(whoami) on $(hostname)"
        shell: sh
        uses: docker://golang:1.20.3-alpine3.17
